### PR TITLE
proposed changes in the project structure, unit tests

### PR DESCRIPTION
**Pull request by NataliaBondarenko**
proposed changes in the project structure, unit tests, dataset for tests, gitignore

### CODE REVIEW

**Comment by NataliaBondarenko** [comment]
Hello! Please, check out changes in the project structure. Tests are usually stored in a separate folder. Accordingly, you need to import the parser and the main function into test files. Therefore, I propose to make changes to be able to automate the search for bugs

**Comment by NataliaBondarenko** [comment]
on fork  https://github.com/NataliaBondarenko/Count-files

**Comment by victordomingos** [comment]
Hi! You have done a lot of work. Thanks again for contributing. 

I have a question. Now that the application is composed of more that one file shouldn’t it be made into a package, with all the code separated from tests, README file...? That would probably make easier the installation. I must confess I never submitted anything to Pypi, so I have no experience with setup.py files and the rest of the process, but feels to me like we should further separate executable files from documentation and tests. 

What do you think?

**Comment by NataliaBondarenko** [comment]
https://github.com/pypa/sampleproject/blob/master/setup.py
line 128.  Do not worry :)

**Comment by NataliaBondarenko** [comment]
Thank you for your cooperation. I am also interested in this project.

**Pull request merged**
